#!/usr/bin/env bash
# script to be set redirecting to another page.

sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
replacemant_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$replacemant_string/" /etc/nginx/sites-available/default
sudo service nginx restart
