#!/usr/bin/env bash
# duplicate web-01 to web-02
sudo apt-get update
sudo apt-get install -y nginx

sudo mkdir -p /var/www/html

echo "Hello World!" | sudo tee /var/www/html/index.html

echo "Ceci n'est pas une page" | sudo tee /var/www/html/error_404.html

sudo cp /etc/nginx/sites-enabled/default /etc/nginx/sites-enabled/default.backup

server_config=\
"server {
		listen 80 default_server;
		listen [::]:80 default_server;
		root /var/www/html;
		index index.html index.htm index.nginx-debian.html;
		server_name _;
		add_header X-Served-By \$hostname;
		location / {
			try_files \$uri \$uri/ =404;
		}
		if (\$request_filename ~ redirect_me) {
			rewrite ^ https://th3-gr00t.tk/ permanent;
		}
		error_page 404 /error_404.html;
		location = /error_404.html {
			internal;
		}
}"

echo "$server_config" | sudo tee /etc/nginx/sites-enabled/default > /dev/null

if [ "$(pgrep -c nginx)" -le 0 ]; then
	sudo service nginx start
else
	sudo service nginx restart
fi
