#!/usr/bin/env bash

# Function to check if haproxy is installed
is_installed() {
    dpkg -l | grep -qw "$1"
}

# Update package list
sudo apt-get -y update

# Check if haproxy is installed; if not, install it
if ! is_installed "haproxy"; then
    sudo apt-get install -y haproxy
else
    echo "haproxy is already installed."
fi

# Configure haproxy
echo "
    frontend cfg_front
        bind *:80
        mode http
        default_backend cfg_back
    backend cfg_back
        balance roundrobin
        server 374415-web-01 54.83.139.226:80 check
        server 374415-web-02 35.153.16.228:80 check
" | sudo tee /etc/haproxy/haproxy.cfg

# Restart haproxy service
sudo service haproxy restart
