#!/usr/bin/env bash
#this script creates a file /var/run/holbertonscript.pid containing the PID of the script
# display "To infinity and beyond" indefinitely
# displays "I hate the kill command" when receiving a SIGTERM signal
# displays "Y U no love me?!" when receiving a SIGINT signal
# deletes the file /var/run/holbertonscript.pid and terminates itself when receiving a SIGQUIT signal
sudo sh -c 'echo $$ > /var/run/myscript.pid'
trap 'echo "I hate the kill command";sudo rm -f /var/run/myscript.pid;exit 0' SIGTERM
trap 'sudo rm -f /var/run/myscript.pid;exit 0' SIGQUIT 
trap 'echo "Y U no love me?!";exit 0' SIGINT
while true
do
    echo "To infinity and beyond"
    sleep 2
done
