#!/usr/bin/env bash
# This script is displaying from 1 to 20 with bad luck from China, Japan and Italy for the 4th, 9th and 17th loop iterations.
i=1
while [ $i -lt 21 ]; do
    echo $i
    case $i in
        4)
            echo "bad luck from China"
            ;;
        9)
            echo "bad luck from Japan"
            ;;
        17)
            echo "bad luck from Italy"
            ;;
    esac
    ((i++))

done